### ISSUE TITLE
No submodule mapping found for Vundle

### ISSUE THREAD

**Issue by apburton84** [scrooloose/vimfiles#13]
cd ~/.vim && git submodule init && git submodule update

**No submodule mapping found in .gitmodules for path 'bundle/Vundle.vim'**

any help would be appreciated

**Comment by irishloop** [comment]
Same error, Ubuntu 14.04.

**Comment by apburton84** [comment]
@irishloop The following resolved the issue for me

    # git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

and then

    # vim +PluginInstall +qall

**Comment by apburton84** [comment]
https://github.com/scrooloose/vimfiles/pull/14 has been merged and should resolve this issue, @irishloop can you confirm ?

**Comment by irishloop** [comment]
Works for me, thanks!
